base_url = "https://example.com"
title = "Serene Demo Site"
description = "Demo site of zola theme serene."
default_language = "en"
compile_sass = true
minify_html = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[extra]
name = "Daenerys Targaryen"
id = "daenerys"
bio = "Queen / Khaleesi / Protector"
avatar = "img/avatar.png"

show_id = true
show_projects = true
show_pgp = false
blog_icon = ""
projects_icon = ""

links = [
    {name = "GitHub", icon = "github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "mail-line", url = "mailto:<your-email-address>"}
    # Your can add more links
]

only_light_mode = false
only_dark_mode = false
blur_effect = true
comment = true
toc = true
author_info_under_post = false
outdate_warn = false
outdate_warn_days = 120


# comment config

# analysic config

