base_url = "https://example.com"
title = "Serene Demo Site"
description = "Demo site of zola theme serene."
default_language = "en"
compile_sass = true
minify_html = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[extra]
name = "Daenerys Targaryen"
id = "daenerys"
bio = "Queen / Khaleesi / Protector"
avatar = "img/avatar.png"

show_id = true
show_projects = false
show_pgp = true # TODO
blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:<your-email-address>"}
    # Your can add more links
]

comment = true # TODO
toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
author_info_under_post = false # TODO
outdate_warn = false # TODO
outdate_warn_days = 120 # TODO
footer_copyright_name = "<your-name>"
footer_copyright_year = "2021"
footer_credits = true

# comment config # TODO

# analysic config # TODO

