# The URL the site will be built for
base_url = "https://example.com"

title = "Serene"
description = "Demo site of zola-theme-serene"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true

feed_filename = "rss.xml"

hard_link_static = true

taxonomies = [
    {name = "tags"},
    {name = "categories"}
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

render_emoji = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
# Put all your custom variables here
name = "Daenerys Targaryen"
id = "daenerys"
bio = "Queen | Khaleesi | Protector"
avatar = "img/avatar.png"
