name = "serene"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/isunjn/serene"
min_version = "0.4.0"
demo = ""

[author]
name = "isunjn"
homepage = "https://github.com/isunjn"

[extra]
name = "xxxx"
id = "xxxx"
bio = "xxxx"
avatar = "img/avatar.webp"

show_id = true
show_projects = true

blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:<your-email-address>"}
]

toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
cc_license = false
cc_license_statement = "This work is licensed under [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."

feed_in_blog_section = true

outdate_warn = false
outdate_warn_days = 120
outdate_warn_text1 = "Note: This article was last updated "
outdate_warn_text2 = " days ago and may be out of date."

footer_copyright_name = "<your-name>"
footer_copyright_year = "2021"
# footer_custom = "xxxxxxxx"
footer_credits = true

comment = "none"  # gitalk / disqus / disqus_js
analytics = "none"  # google_analytics / cloudflare_web_analytics / umami / baidu_tongji


#======================= Comment =======================

[extra.gitalk]
client_id = "xxxxxxxx"
client_secret = "xxxxxxxx"
repo = "xxxxxxxx"
owner = "xxxx"
admin = ["xxxx"]
distraction_free_mode = false
per_page = 10
page_direction = "first"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

[extra.disqus]
shortname = "xxxx"

[extra.disqus_js]
shortname = "xxxx"
apikey = "xxxx"
# site_name = "xxxx"
# identifier = "xxxx"
# url = "xxxx"
# title = "xxxx"
# api = "xxxx"
# nesting = 4
# nocomment = "xxxx"
# admin = "xxxx"
# admin_label = "xxxx"


#======================= Analytics =======================

[extra.google_analytics]
id = "G-XXXXXXXX"  # or UA-XXXXXXXX

[extra.cloudflare_web_analytics]
token = "xxxxxxxx"

[extra.umami]
website_id = "xxxxx-xxxx-xxxxx"
src = "https://xxxxxxxxxxx/umami.js"

[extra.baidu_tongji]
token = "xxxxxxxx"