name = "serene"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/isunjn/serene"
min_version = "0.4.0"
demo = ""

[author]
name = "isunjn"
homepage = "https://github.com/isunjn"

[extra]
name = "xxxx"
id = "xxxx"
bio = "xxxx"
avatar = "img/avatar.png"

show_id = true
show_projects = false #TODO
show_pgp = false # TODO
blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:<your-email-address>"}
    # Your can add more links
]

toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
author_info_under_post = false # TODO
cc_license = true
cc_license_info = "This work is licensed under [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/), please contact the author and indicate the original link for reprinting."

outdate_warn = true
outdate_warn_days = 120
outdate_warn_text1 = "Note: This article was last updated "
outdate_warn_text2 = " days ago and may be out of date."

footer_copyright_name = "<your-name>"
footer_copyright_year = "2021"
footer_credits = true

# comment config # TODO
comment = "none"

[extra.gitalk]
clientID = "xxxxxxxx"
clientSecret = "xxxxxxxx"
repo = "xxxxxxxx"
owner = "xxxx"
admin = ["xxxx"]
distractionFreeMode = false

# analytics config # TODO

analytics = "xxxx"

[extra.umami]
data_website_id = "xxxxx-xxxx-xxxxx"
src = "https://xxxxxxxxxxx/umami.js"